-- Run this in Supabase SQL Editor.
-- Table for Easy India Packers Movers enquiry form leads.

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  mobile text not null,
  moving_from text not null,
  moving_to text not null,
  moving_date date,
  service_type text,
  message text,
  source text default 'shifteasyindia.com'
);

alter table public.enquiries enable row level security;

drop policy if exists "Allow public enquiry insert" on public.enquiries;

create policy "Allow public enquiry insert"
on public.enquiries
for insert
to anon
with check (true);

-- Optional: only authenticated Supabase users can read leads in dashboard/API.
drop policy if exists "Allow authenticated enquiry read" on public.enquiries;

create policy "Allow authenticated enquiry read"
on public.enquiries
for select
to authenticated
using (true);
